pipeline {
    agent any

	tools {
		maven 'maven3.6.1'
	}

//	environment {
//		M2_INSTALL = "/home/gamut/Distros/apache-maven-3.6.1/bin/mvn"
//	}

    stages {
		stage('Clone-Repo') {
			steps {
				checkout scm
			}
		}
		stage('Build') {
	    	steps {
				sh 'mvn install -DskipTests'
			}
	    }
		stage('Unit Tests') {
			steps {
				sh 'mvn surefire:test'
			}
		}
		stage('Deployment') {
	    	steps {
				sh 'sshpass -p "smartvalue99" scp target/gamutkart.war gamut@172.17.0.2:/home/gamut/Distros/apache-tomcat-8.5.43/webapps'
				sh 'sshpass -p "smartvalue99" ssh gamut@172.17.0.2 "JAVA_HOME=/home/gamut/Distros/jdk1.8.0_211" "/home/gamut/Distros/apache-tomcat-8.5.43/bin/startup.sh"'
	    	}
		}
    }
}
